language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/ConradIrwin/panicwrap
  - go get github.com/mitchellh/osext
  - go get github.com/bitly/go-simplejson
  - go get github.com/revel/revel
